package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BrandMaster generated by hbm2java
 */
@Entity
@Table(name="brand_master"
    ,catalog="raf"
)
public class BrandMaster  implements java.io.Serializable {


     private Integer brandId;
     private String brandName;
     private String nrvPerStrip;
     private String status;
     private String loginid;

    public BrandMaster() {
    }

	
    public BrandMaster(String brandName, String nrvPerStrip, String status) {
        this.brandName = brandName;
        this.nrvPerStrip = nrvPerStrip;
        this.status = status;
    }
    public BrandMaster(String brandName, String nrvPerStrip, String status, String loginid) {
       this.brandName = brandName;
       this.nrvPerStrip = nrvPerStrip;
       this.status = status;
       this.loginid = loginid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="brand_id", unique=true, nullable=false)
    public Integer getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    
    @Column(name="brand_name", nullable=false, length=45)
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    
    @Column(name="nrv_per_strip", nullable=false, length=45)
    public String getNrvPerStrip() {
        return this.nrvPerStrip;
    }
    
    public void setNrvPerStrip(String nrvPerStrip) {
        this.nrvPerStrip = nrvPerStrip;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="loginid", length=45)
    public String getLoginid() {
        return this.loginid;
    }
    
    public void setLoginid(String loginid) {
        this.loginid = loginid;
    }




}


