package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CheckMaster generated by hbm2java
 */
@Entity
@Table(name="check_master"
    ,catalog="raf"
)
public class CheckMaster  implements java.io.Serializable {


     private Integer chId;
     private Date repdate;
     private String loginid;
     private int rid;

    public CheckMaster() {
    }

    public CheckMaster(Date repdate, String loginid, int rid) {
       this.repdate = repdate;
       this.loginid = loginid;
       this.rid = rid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ch_id", unique=true, nullable=false)
    public Integer getChId() {
        return this.chId;
    }
    
    public void setChId(Integer chId) {
        this.chId = chId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="repdate", nullable=false, length=10)
    public Date getRepdate() {
        return this.repdate;
    }
    
    public void setRepdate(Date repdate) {
        this.repdate = repdate;
    }

    
    @Column(name="loginid", nullable=false, length=45)
    public String getLoginid() {
        return this.loginid;
    }
    
    public void setLoginid(String loginid) {
        this.loginid = loginid;
    }

    
    @Column(name="rid", nullable=false)
    public int getRid() {
        return this.rid;
    }
    
    public void setRid(int rid) {
        this.rid = rid;
    }




}


