package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChemistMaster generated by hbm2java
 */
@Entity
@Table(name="chemist_master"
    ,catalog="raf"
)
public class ChemistMaster  implements java.io.Serializable {


     private Integer chId;
     private Loginmaster loginmaster;
     private String chemistName;
     private String city;
     private String state;
     private String pin;
     private String address;
     private String mobile;
     private String landline;
     private Date creationDate;
     private String status;
     private String deleteoperation;

    public ChemistMaster() {
    }

	
    public ChemistMaster(String chemistName, String city, String state, String address, String mobile, Date creationDate) {
        this.chemistName = chemistName;
        this.city = city;
        this.state = state;
        this.address = address;
        this.mobile = mobile;
        this.creationDate = creationDate;
    }
    public ChemistMaster(Loginmaster loginmaster, String chemistName, String city, String state, String pin, String address, String mobile, String landline, Date creationDate, String status, String deleteoperation) {
       this.loginmaster = loginmaster;
       this.chemistName = chemistName;
       this.city = city;
       this.state = state;
       this.pin = pin;
       this.address = address;
       this.mobile = mobile;
       this.landline = landline;
       this.creationDate = creationDate;
       this.status = status;
       this.deleteoperation = deleteoperation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ch_id", unique=true, nullable=false)
    public Integer getChId() {
        return this.chId;
    }
    
    public void setChId(Integer chId) {
        this.chId = chId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loginid")
    public Loginmaster getLoginmaster() {
        return this.loginmaster;
    }
    
    public void setLoginmaster(Loginmaster loginmaster) {
        this.loginmaster = loginmaster;
    }

    
    @Column(name="chemist_name", nullable=false, length=200)
    public String getChemistName() {
        return this.chemistName;
    }
    
    public void setChemistName(String chemistName) {
        this.chemistName = chemistName;
    }

    
    @Column(name="city", nullable=false, length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="state", nullable=false, length=45)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="pin", length=45)
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }

    
    @Column(name="address", nullable=false, length=75)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="mobile", nullable=false, length=45)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="landline", length=45)
    public String getLandline() {
        return this.landline;
    }
    
    public void setLandline(String landline) {
        this.landline = landline;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=10)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="deleteoperation", length=45)
    public String getDeleteoperation() {
        return this.deleteoperation;
    }
    
    public void setDeleteoperation(String deleteoperation) {
        this.deleteoperation = deleteoperation;
    }




}


