package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExpenseMaster generated by hbm2java
 */
@Entity
@Table(name="expense_master"
    ,catalog="raf"
)
public class ExpenseMaster  implements java.io.Serializable {


     private Integer exId;
     private Loginmaster loginmaster;
     private Date exDate;
     private String modeOfTransport;
     private int fare;
     private int allowances;
     private int misc;
     private String creationDate;
     private String status;
     private String noOfKilomeeter;
     private String editoperation;
     private String typeOfLogin;
     private String station;

    public ExpenseMaster() {
    }

	
    public ExpenseMaster(Loginmaster loginmaster, Date exDate, String modeOfTransport, int fare, int allowances, int misc, String creationDate, String status, String noOfKilomeeter, String editoperation, String station) {
        this.loginmaster = loginmaster;
        this.exDate = exDate;
        this.modeOfTransport = modeOfTransport;
        this.fare = fare;
        this.allowances = allowances;
        this.misc = misc;
        this.creationDate = creationDate;
        this.status = status;
        this.noOfKilomeeter = noOfKilomeeter;
        this.editoperation = editoperation;
        this.station = station;
    }
    public ExpenseMaster(Loginmaster loginmaster, Date exDate, String modeOfTransport, int fare, int allowances, int misc, String creationDate, String status, String noOfKilomeeter, String editoperation, String typeOfLogin, String station) {
       this.loginmaster = loginmaster;
       this.exDate = exDate;
       this.modeOfTransport = modeOfTransport;
       this.fare = fare;
       this.allowances = allowances;
       this.misc = misc;
       this.creationDate = creationDate;
       this.status = status;
       this.noOfKilomeeter = noOfKilomeeter;
       this.editoperation = editoperation;
       this.typeOfLogin = typeOfLogin;
       this.station = station;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ex_id", unique=true, nullable=false)
    public Integer getExId() {
        return this.exId;
    }
    
    public void setExId(Integer exId) {
        this.exId = exId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loginid", nullable=false)
    public Loginmaster getLoginmaster() {
        return this.loginmaster;
    }
    
    public void setLoginmaster(Loginmaster loginmaster) {
        this.loginmaster = loginmaster;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ex_date", nullable=false, length=10)
    public Date getExDate() {
        return this.exDate;
    }
    
    public void setExDate(Date exDate) {
        this.exDate = exDate;
    }

    
    @Column(name="mode_of_transport", nullable=false, length=2000)
    public String getModeOfTransport() {
        return this.modeOfTransport;
    }
    
    public void setModeOfTransport(String modeOfTransport) {
        this.modeOfTransport = modeOfTransport;
    }

    
    @Column(name="fare", nullable=false)
    public int getFare() {
        return this.fare;
    }
    
    public void setFare(int fare) {
        this.fare = fare;
    }

    
    @Column(name="allowances", nullable=false)
    public int getAllowances() {
        return this.allowances;
    }
    
    public void setAllowances(int allowances) {
        this.allowances = allowances;
    }

    
    @Column(name="misc", nullable=false)
    public int getMisc() {
        return this.misc;
    }
    
    public void setMisc(int misc) {
        this.misc = misc;
    }

    
    @Column(name="creation_date", nullable=false, length=2000)
    public String getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="no_of_kilomeeter", nullable=false, length=45)
    public String getNoOfKilomeeter() {
        return this.noOfKilomeeter;
    }
    
    public void setNoOfKilomeeter(String noOfKilomeeter) {
        this.noOfKilomeeter = noOfKilomeeter;
    }

    
    @Column(name="editoperation", nullable=false, length=45)
    public String getEditoperation() {
        return this.editoperation;
    }
    
    public void setEditoperation(String editoperation) {
        this.editoperation = editoperation;
    }

    
    @Column(name="type_of_login", length=45)
    public String getTypeOfLogin() {
        return this.typeOfLogin;
    }
    
    public void setTypeOfLogin(String typeOfLogin) {
        this.typeOfLogin = typeOfLogin;
    }

    
    @Column(name="station", nullable=false, length=45)
    public String getStation() {
        return this.station;
    }
    
    public void setStation(String station) {
        this.station = station;
    }




}


