package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LeaveMaster generated by hbm2java
 */
@Entity
@Table(name="leave_master"
    ,catalog="raf"
)
public class LeaveMaster  implements java.io.Serializable {


     private Integer lvId;
     private Loginmaster loginmaster;
     private Date lvDate;
     private String noOfDays;
     private String reason;
     private Date creationDate;
     private String status;

    public LeaveMaster() {
    }

    public LeaveMaster(Loginmaster loginmaster, Date lvDate, String noOfDays, String reason, Date creationDate, String status) {
       this.loginmaster = loginmaster;
       this.lvDate = lvDate;
       this.noOfDays = noOfDays;
       this.reason = reason;
       this.creationDate = creationDate;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lv_id", unique=true, nullable=false)
    public Integer getLvId() {
        return this.lvId;
    }
    
    public void setLvId(Integer lvId) {
        this.lvId = lvId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loginid", nullable=false)
    public Loginmaster getLoginmaster() {
        return this.loginmaster;
    }
    
    public void setLoginmaster(Loginmaster loginmaster) {
        this.loginmaster = loginmaster;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lv_date", nullable=false, length=10)
    public Date getLvDate() {
        return this.lvDate;
    }
    
    public void setLvDate(Date lvDate) {
        this.lvDate = lvDate;
    }

    
    @Column(name="no_of_days", nullable=false, length=40)
    public String getNoOfDays() {
        return this.noOfDays;
    }
    
    public void setNoOfDays(String noOfDays) {
        this.noOfDays = noOfDays;
    }

    
    @Column(name="reason", nullable=false, length=200)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=10)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


