package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loginmaster generated by hbm2java
 */
@Entity
@Table(name="loginmaster"
    ,catalog="raf"
)
public class Loginmaster  implements java.io.Serializable {


     private Integer loginid;
     private String password;
     private String emailid;
     private String type;
     private String status;
     private Set<LeaveMaster> leaveMasters = new HashSet<LeaveMaster>(0);
     private Set<ChemistMaster> chemistMasters = new HashSet<ChemistMaster>(0);
     private Set<StockistMaster> stockistMasters = new HashSet<StockistMaster>(0);
     private Set<DoctorMaster> doctorMasters = new HashSet<DoctorMaster>(0);
     private Set<TourMaster> tourMasters = new HashSet<TourMaster>(0);
     private Set<ExpenseMaster> expenseMasters = new HashSet<ExpenseMaster>(0);

    public Loginmaster() {
    }

	
    public Loginmaster(String password, String emailid, String type, String status) {
        this.password = password;
        this.emailid = emailid;
        this.type = type;
        this.status = status;
    }
    public Loginmaster(String password, String emailid, String type, String status, Set<LeaveMaster> leaveMasters, Set<ChemistMaster> chemistMasters, Set<StockistMaster> stockistMasters, Set<DoctorMaster> doctorMasters, Set<TourMaster> tourMasters, Set<ExpenseMaster> expenseMasters) {
       this.password = password;
       this.emailid = emailid;
       this.type = type;
       this.status = status;
       this.leaveMasters = leaveMasters;
       this.chemistMasters = chemistMasters;
       this.stockistMasters = stockistMasters;
       this.doctorMasters = doctorMasters;
       this.tourMasters = tourMasters;
       this.expenseMasters = expenseMasters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="loginid", unique=true, nullable=false)
    public Integer getLoginid() {
        return this.loginid;
    }
    
    public void setLoginid(Integer loginid) {
        this.loginid = loginid;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="emailid", nullable=false, length=45)
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }

    
    @Column(name="type", nullable=false, length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loginmaster")
    public Set<LeaveMaster> getLeaveMasters() {
        return this.leaveMasters;
    }
    
    public void setLeaveMasters(Set<LeaveMaster> leaveMasters) {
        this.leaveMasters = leaveMasters;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loginmaster")
    public Set<ChemistMaster> getChemistMasters() {
        return this.chemistMasters;
    }
    
    public void setChemistMasters(Set<ChemistMaster> chemistMasters) {
        this.chemistMasters = chemistMasters;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loginmaster")
    public Set<StockistMaster> getStockistMasters() {
        return this.stockistMasters;
    }
    
    public void setStockistMasters(Set<StockistMaster> stockistMasters) {
        this.stockistMasters = stockistMasters;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loginmaster")
    public Set<DoctorMaster> getDoctorMasters() {
        return this.doctorMasters;
    }
    
    public void setDoctorMasters(Set<DoctorMaster> doctorMasters) {
        this.doctorMasters = doctorMasters;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loginmaster")
    public Set<TourMaster> getTourMasters() {
        return this.tourMasters;
    }
    
    public void setTourMasters(Set<TourMaster> tourMasters) {
        this.tourMasters = tourMasters;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loginmaster")
    public Set<ExpenseMaster> getExpenseMasters() {
        return this.expenseMasters;
    }
    
    public void setExpenseMasters(Set<ExpenseMaster> expenseMasters) {
        this.expenseMasters = expenseMasters;
    }




}


