package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReportingMaster generated by hbm2java
 */
@Entity
@Table(name="reporting_master"
    ,catalog="raf"
)
public class ReportingMaster  implements java.io.Serializable {


     private Integer reportingId;
     private String reportingtype;
     private String typename;
     private String workingwith;
     private String repdate;
     private String status;
     private int loginid;
     private String work;
     private Integer expid;
     private String logintype;
     private String workingLocation;
     private String typeOfStation;

    public ReportingMaster() {
    }

	
    public ReportingMaster(String reportingtype, String typename, String workingwith, String repdate, String status, int loginid, String work, String logintype, String workingLocation, String typeOfStation) {
        this.reportingtype = reportingtype;
        this.typename = typename;
        this.workingwith = workingwith;
        this.repdate = repdate;
        this.status = status;
        this.loginid = loginid;
        this.work = work;
        this.logintype = logintype;
        this.workingLocation = workingLocation;
        this.typeOfStation = typeOfStation;
    }
    public ReportingMaster(String reportingtype, String typename, String workingwith, String repdate, String status, int loginid, String work, Integer expid, String logintype, String workingLocation, String typeOfStation) {
       this.reportingtype = reportingtype;
       this.typename = typename;
       this.workingwith = workingwith;
       this.repdate = repdate;
       this.status = status;
       this.loginid = loginid;
       this.work = work;
       this.expid = expid;
       this.logintype = logintype;
       this.workingLocation = workingLocation;
       this.typeOfStation = typeOfStation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="reporting_id", unique=true, nullable=false)
    public Integer getReportingId() {
        return this.reportingId;
    }
    
    public void setReportingId(Integer reportingId) {
        this.reportingId = reportingId;
    }

    
    @Column(name="reportingtype", nullable=false, length=45)
    public String getReportingtype() {
        return this.reportingtype;
    }
    
    public void setReportingtype(String reportingtype) {
        this.reportingtype = reportingtype;
    }

    
    @Column(name="typename", nullable=false, length=45)
    public String getTypename() {
        return this.typename;
    }
    
    public void setTypename(String typename) {
        this.typename = typename;
    }

    
    @Column(name="workingwith", nullable=false, length=45)
    public String getWorkingwith() {
        return this.workingwith;
    }
    
    public void setWorkingwith(String workingwith) {
        this.workingwith = workingwith;
    }

    
    @Column(name="repdate", nullable=false, length=45)
    public String getRepdate() {
        return this.repdate;
    }
    
    public void setRepdate(String repdate) {
        this.repdate = repdate;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="loginid", nullable=false)
    public int getLoginid() {
        return this.loginid;
    }
    
    public void setLoginid(int loginid) {
        this.loginid = loginid;
    }

    
    @Column(name="work", nullable=false, length=45)
    public String getWork() {
        return this.work;
    }
    
    public void setWork(String work) {
        this.work = work;
    }

    
    @Column(name="expid")
    public Integer getExpid() {
        return this.expid;
    }
    
    public void setExpid(Integer expid) {
        this.expid = expid;
    }

    
    @Column(name="logintype", nullable=false, length=45)
    public String getLogintype() {
        return this.logintype;
    }
    
    public void setLogintype(String logintype) {
        this.logintype = logintype;
    }

    
    @Column(name="working_location", nullable=false, length=45)
    public String getWorkingLocation() {
        return this.workingLocation;
    }
    
    public void setWorkingLocation(String workingLocation) {
        this.workingLocation = workingLocation;
    }

    
    @Column(name="type_of_station", nullable=false, length=45)
    public String getTypeOfStation() {
        return this.typeOfStation;
    }
    
    public void setTypeOfStation(String typeOfStation) {
        this.typeOfStation = typeOfStation;
    }




}


