package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Saledata generated by hbm2java
 */
@Entity
@Table(name="saledata"
    ,catalog="raf"
)
public class Saledata  implements java.io.Serializable {


     private Integer saleid;
     private String brandName;
     private String noOfStrip;
     private String nrv;
     private String month;
     private String year;
     private String totalValue;
     private String saleType;
     private int loginId;
     private Date datt;

    public Saledata() {
    }

    public Saledata(String brandName, String noOfStrip, String nrv, String month, String year, String totalValue, String saleType, int loginId, Date datt) {
       this.brandName = brandName;
       this.noOfStrip = noOfStrip;
       this.nrv = nrv;
       this.month = month;
       this.year = year;
       this.totalValue = totalValue;
       this.saleType = saleType;
       this.loginId = loginId;
       this.datt = datt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="saleid", unique=true, nullable=false)
    public Integer getSaleid() {
        return this.saleid;
    }
    
    public void setSaleid(Integer saleid) {
        this.saleid = saleid;
    }

    
    @Column(name="brand_name", nullable=false, length=45)
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    
    @Column(name="no_of_strip", nullable=false, length=45)
    public String getNoOfStrip() {
        return this.noOfStrip;
    }
    
    public void setNoOfStrip(String noOfStrip) {
        this.noOfStrip = noOfStrip;
    }

    
    @Column(name="nrv", nullable=false, length=45)
    public String getNrv() {
        return this.nrv;
    }
    
    public void setNrv(String nrv) {
        this.nrv = nrv;
    }

    
    @Column(name="month", nullable=false, length=45)
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }

    
    @Column(name="year", nullable=false, length=45)
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }

    
    @Column(name="total_value", nullable=false, length=45)
    public String getTotalValue() {
        return this.totalValue;
    }
    
    public void setTotalValue(String totalValue) {
        this.totalValue = totalValue;
    }

    
    @Column(name="sale_type", nullable=false, length=45)
    public String getSaleType() {
        return this.saleType;
    }
    
    public void setSaleType(String saleType) {
        this.saleType = saleType;
    }

    
    @Column(name="login_id", nullable=false)
    public int getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(int loginId) {
        this.loginId = loginId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datt", nullable=false, length=10)
    public Date getDatt() {
        return this.datt;
    }
    
    public void setDatt(Date datt) {
        this.datt = datt;
    }




}


