package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StockDetail generated by hbm2java
 */
@Entity
@Table(name="stock_detail"
    ,catalog="raf"
)
public class StockDetail  implements java.io.Serializable {


     private int stockdetailId;
     private String compName;
     private String compDesc;
     private String remark;
     private String listedDate;
     private Set<Stock> stocks = new HashSet<Stock>(0);

    public StockDetail() {
    }

	
    public StockDetail(int stockdetailId) {
        this.stockdetailId = stockdetailId;
    }
    public StockDetail(int stockdetailId, String compName, String compDesc, String remark, String listedDate, Set<Stock> stocks) {
       this.stockdetailId = stockdetailId;
       this.compName = compName;
       this.compDesc = compDesc;
       this.remark = remark;
       this.listedDate = listedDate;
       this.stocks = stocks;
    }
   
     @Id 

    
    @Column(name="stockdetail_Id", unique=true, nullable=false)
    public int getStockdetailId() {
        return this.stockdetailId;
    }
    
    public void setStockdetailId(int stockdetailId) {
        this.stockdetailId = stockdetailId;
    }

    
    @Column(name="compName", length=45)
    public String getCompName() {
        return this.compName;
    }
    
    public void setCompName(String compName) {
        this.compName = compName;
    }

    
    @Column(name="compDesc", length=45)
    public String getCompDesc() {
        return this.compDesc;
    }
    
    public void setCompDesc(String compDesc) {
        this.compDesc = compDesc;
    }

    
    @Column(name="remark", length=45)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="listedDate", length=45)
    public String getListedDate() {
        return this.listedDate;
    }
    
    public void setListedDate(String listedDate) {
        this.listedDate = listedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stockDetail")
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }




}


