package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name="stock"
    ,catalog="raf"
)
public class Stock  implements java.io.Serializable {


     private int stockId;
     private StockDetail stockDetail;
     private String stockCode;
     private String stockName;

    public Stock() {
    }

	
    public Stock(int stockId) {
        this.stockId = stockId;
    }
    public Stock(int stockId, StockDetail stockDetail, String stockCode, String stockName) {
       this.stockId = stockId;
       this.stockDetail = stockDetail;
       this.stockCode = stockCode;
       this.stockName = stockName;
    }
   
     @Id 

    
    @Column(name="stockId", unique=true, nullable=false)
    public int getStockId() {
        return this.stockId;
    }
    
    public void setStockId(int stockId) {
        this.stockId = stockId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stockdetailid")
    public StockDetail getStockDetail() {
        return this.stockDetail;
    }
    
    public void setStockDetail(StockDetail stockDetail) {
        this.stockDetail = stockDetail;
    }

    
    @Column(name="stockCode", length=45)
    public String getStockCode() {
        return this.stockCode;
    }
    
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode;
    }

    
    @Column(name="stockName", length=45)
    public String getStockName() {
        return this.stockName;
    }
    
    public void setStockName(String stockName) {
        this.stockName = stockName;
    }




}


