package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TourMaster generated by hbm2java
 */
@Entity
@Table(name="tour_master"
    ,catalog="raf"
)
public class TourMaster  implements java.io.Serializable {


     private Integer tourId;
     private Loginmaster loginmaster;
     private String tourDate;
     private String placeOfWork;
     private String status;
     private String station;

    public TourMaster() {
    }

    public TourMaster(Loginmaster loginmaster, String tourDate, String placeOfWork, String status, String station) {
       this.loginmaster = loginmaster;
       this.tourDate = tourDate;
       this.placeOfWork = placeOfWork;
       this.status = status;
       this.station = station;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tour_id", unique=true, nullable=false)
    public Integer getTourId() {
        return this.tourId;
    }
    
    public void setTourId(Integer tourId) {
        this.tourId = tourId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loginid", nullable=false)
    public Loginmaster getLoginmaster() {
        return this.loginmaster;
    }
    
    public void setLoginmaster(Loginmaster loginmaster) {
        this.loginmaster = loginmaster;
    }

    
    @Column(name="tour_date", nullable=false, length=45)
    public String getTourDate() {
        return this.tourDate;
    }
    
    public void setTourDate(String tourDate) {
        this.tourDate = tourDate;
    }

    
    @Column(name="place_of_work", nullable=false, length=45)
    public String getPlaceOfWork() {
        return this.placeOfWork;
    }
    
    public void setPlaceOfWork(String placeOfWork) {
        this.placeOfWork = placeOfWork;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="station", nullable=false, length=45)
    public String getStation() {
        return this.station;
    }
    
    public void setStation(String station) {
        this.station = station;
    }




}


