package com.example.hibeex.entity;
// Generated 4 Jul, 2019 1:49:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TravelMaster generated by hbm2java
 */
@Entity
@Table(name="travel_master"
    ,catalog="raf"
)
public class TravelMaster  implements java.io.Serializable {


     private Integer trId;
     private String travel;

    public TravelMaster() {
    }

    public TravelMaster(String travel) {
       this.travel = travel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tr_id", unique=true, nullable=false)
    public Integer getTrId() {
        return this.trId;
    }
    
    public void setTrId(Integer trId) {
        this.trId = trId;
    }

    
    @Column(name="travel", nullable=false, length=45)
    public String getTravel() {
        return this.travel;
    }
    
    public void setTravel(String travel) {
        this.travel = travel;
    }




}


